# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.sample import Sample  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, status: Sample=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param id: The id of this InlineResponse2001.  # noqa: E501
        :type id: str
        :param status: The status of this InlineResponse2001.  # noqa: E501
        :type status: Sample
        """
        self.swagger_types = {
            'id': str,
            'status': Sample
        }

        self.attribute_map = {
            'id': 'id',
            'status': 'status'
        }

        self._id = id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this InlineResponse2001.


        :return: The id of this InlineResponse2001.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this InlineResponse2001.


        :param id: The id of this InlineResponse2001.
        :type id: str
        """

        self._id = id

    @property
    def status(self) -> Sample:
        """Gets the status of this InlineResponse2001.


        :return: The status of this InlineResponse2001.
        :rtype: Sample
        """
        return self._status

    @status.setter
    def status(self, status: Sample):
        """Sets the status of this InlineResponse2001.


        :param status: The status of this InlineResponse2001.
        :type status: Sample
        """

        self._status = status
