# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.result import Result  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, result: Result=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param id: The id of this InlineResponse2002.  # noqa: E501
        :type id: str
        :param result: The result of this InlineResponse2002.  # noqa: E501
        :type result: Result
        """
        self.swagger_types = {
            'id': str,
            'result': Result
        }

        self.attribute_map = {
            'id': 'id',
            'result': 'result'
        }

        self._id = id
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this InlineResponse2002.


        :return: The id of this InlineResponse2002.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this InlineResponse2002.


        :param id: The id of this InlineResponse2002.
        :type id: str
        """

        self._id = id

    @property
    def result(self) -> Result:
        """Gets the result of this InlineResponse2002.


        :return: The result of this InlineResponse2002.
        :rtype: Result
        """
        return self._result

    @result.setter
    def result(self, result: Result):
        """Sets the result of this InlineResponse2002.


        :param result: The result of this InlineResponse2002.
        :type result: Result
        """

        self._result = result
