# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Sample(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, author_email: str=None, created: date=None, last_updated: date=None, path_one: str=None, path_two: str=None):  # noqa: E501
        """Sample - a model defined in Swagger

        :param id: The id of this Sample.  # noqa: E501
        :type id: str
        :param author_email: The author_email of this Sample.  # noqa: E501
        :type author_email: str
        :param created: The created of this Sample.  # noqa: E501
        :type created: date
        :param last_updated: The last_updated of this Sample.  # noqa: E501
        :type last_updated: date
        :param path_one: The path_one of this Sample.  # noqa: E501
        :type path_one: str
        :param path_two: The path_two of this Sample.  # noqa: E501
        :type path_two: str
        """
        self.swagger_types = {
            'id': str,
            'author_email': str,
            'created': date,
            'last_updated': date,
            'path_one': str,
            'path_two': str
        }

        self.attribute_map = {
            'id': 'id',
            'author_email': 'author_email',
            'created': 'created',
            'last_updated': 'last_updated',
            'path_one': 'path_one',
            'path_two': 'path_two'
        }

        self._id = id
        self._author_email = author_email
        self._created = created
        self._last_updated = last_updated
        self._path_one = path_one
        self._path_two = path_two

    @classmethod
    def from_dict(cls, dikt) -> 'Sample':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Sample of this Sample.  # noqa: E501
        :rtype: Sample
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Sample.


        :return: The id of this Sample.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Sample.


        :param id: The id of this Sample.
        :type id: str
        """

        self._id = id

    @property
    def author_email(self) -> str:
        """Gets the author_email of this Sample.


        :return: The author_email of this Sample.
        :rtype: str
        """
        return self._author_email

    @author_email.setter
    def author_email(self, author_email: str):
        """Sets the author_email of this Sample.


        :param author_email: The author_email of this Sample.
        :type author_email: str
        """

        self._author_email = author_email

    @property
    def created(self) -> date:
        """Gets the created of this Sample.


        :return: The created of this Sample.
        :rtype: date
        """
        return self._created

    @created.setter
    def created(self, created: date):
        """Sets the created of this Sample.


        :param created: The created of this Sample.
        :type created: date
        """

        self._created = created

    @property
    def last_updated(self) -> date:
        """Gets the last_updated of this Sample.


        :return: The last_updated of this Sample.
        :rtype: date
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated: date):
        """Sets the last_updated of this Sample.


        :param last_updated: The last_updated of this Sample.
        :type last_updated: date
        """

        self._last_updated = last_updated

    @property
    def path_one(self) -> str:
        """Gets the path_one of this Sample.


        :return: The path_one of this Sample.
        :rtype: str
        """
        return self._path_one

    @path_one.setter
    def path_one(self, path_one: str):
        """Sets the path_one of this Sample.


        :param path_one: The path_one of this Sample.
        :type path_one: str
        """

        self._path_one = path_one

    @property
    def path_two(self) -> str:
        """Gets the path_two of this Sample.


        :return: The path_two of this Sample.
        :rtype: str
        """
        return self._path_two

    @path_two.setter
    def path_two(self, path_two: str):
        """Sets the path_two of this Sample.


        :param path_two: The path_two of this Sample.
        :type path_two: str
        """

        self._path_two = path_two
