swagger: "2.0"
info:
  description: "This is a metabiom analysis pipeline"
  version: "0.1.0"
  title: "Metabiom"
  contact:
    email: "caspar.gross@med.uni-tuebingen.de"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "petstore.swagger.io"
basePath: "/v1"
tags:
- name: "project"
  description: "Everything about projects"
- name: "status"
  description: "Process status"
schemes:
- "http"
paths:
  /status:
    get:
      tags:
      - "status"
      summary: "Get list of all project statuses"
      operationId: "listAllStatus"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                  format: "integer64"
                status:
                  $ref: "#/definitions/Status"
  /status/{projectId}:
    get:
      tags:
      - "status"
      summary: "Get status for a single project"
      operationId: "getProjectStatus"
      produces:
      - "application/json"
      parameters:
      - name: "projectId"
        in: "path"
        description: "ID of project to return status for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful"
          schema:
            $ref: "#/definitions/Status"
        404:
          description: "project not found"
  /project:
    get:
      tags:
      - "project"
      summary: "Lists all projects"
      operationId: "listAllProjects"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful"
          schema:
            $ref: "#/definitions/Project"
    put:
      tags:
      - "project"
      summary: "Create a new project"
      operationId: "createProject"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "The project to add"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        200:
          description: "returns the project id"
          schema:
            type: "integer"
            format: "int64"
  /project/{projectId}/start:
    patch:
      tags:
      - "project"
      summary: "Start a project"
      operationId: "startProject"
      parameters:
      - in: path
        name: "projectId"
        description: "ID of project to return status for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful"
        503:
          description: "couldn't start job"
          schema:
            description: "error message"
            type: string
      
 

definitions:
  Status:
    type: "string"
    enum:
      - "created"
      - "started"
      - "finished"
      - "error"
  Project:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      author_email:
        type: "string"
      created_date:
        type: "string"
        format: "date"
      last_updated:
        type: "string"
        format: "date"
      probe_type:
        type: "string"
        enum:
        - single
        - multiple
externalDocs:
  description: "Find out more about metabiom"
  url: "http://github.com"