# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uploaded_file=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI

        :param uploaded_file: The uploaded_file of this InlineObject.  # noqa: E501
        :type uploaded_file: file
        """
        self.openapi_types = {
            'uploaded_file': file
        }

        self.attribute_map = {
            'uploaded_file': 'uploaded_file'
        }

        self._uploaded_file = uploaded_file

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object of this InlineObject.  # noqa: E501
        :rtype: InlineObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uploaded_file(self):
        """Gets the uploaded_file of this InlineObject.

        The file to upload.  # noqa: E501

        :return: The uploaded_file of this InlineObject.
        :rtype: file
        """
        return self._uploaded_file

    @uploaded_file.setter
    def uploaded_file(self, uploaded_file):
        """Sets the uploaded_file of this InlineObject.

        The file to upload.  # noqa: E501

        :param uploaded_file: The uploaded_file of this InlineObject.
        :type uploaded_file: file
        """

        self._uploaded_file = uploaded_file
